Options = {
    'Computer_Fundamentals_Quiz': [
        ["Central Processing Unit", "Control Panel Unit", "Central Print Unit", "Computer Processing Utility", "Central Processing Unit"],
        ["Random Access Memory", "Read Access Memory", "Read And Manage", "Run Accept Memory", "Random Access Memory"],
        ["Device that outputs data", "Device that stores data", "Device that sends data into the computer", "Device that processes data", "Device that sends data into the computer"],
        ["It processes data", "It stores files", "It manages hardware and software", "It protects the computer from viruses", "It manages hardware and software"],
        ["Hardware is physical, software is programs", "Software is physical, hardware is code", "Hardware and software are both code", "Software cannot be replaced", "Hardware is physical, software is programs"],
        ["Read Only Memory", "Run On Memory", "Random Output Memory", "Read Often Memory", "Read Only Memory"],
        ["A group of computers connected together", "A single standalone computer", "An external hard drive", "A wireless mouse", "A group of computers connected together"],
        ["To input data", "To output data as hard copy", "To store information", "To connect to the Internet", "To output data as hard copy"],
        ["A programming command", "A folder in Windows", "A collection of data stored as a unit", "A web link", "A collection of data stored as a unit"],
        ["It translates high-level language to machine code", "It stores data", "It connects networks", "It manages hardware", "It translates high-level language to machine code"],
        ["A number system with base 2", "A number system with base 10", "A system used for decimals", "A number system with base 8", "A number system with base 2"],
        ["Performs arithmetic and logical operations", "Stores information", "Controls software", "Inputs data", "Performs arithmetic and logical operations"],
        ["It connects all components of the computer", "It provides electricity", "It stores the operating system", "It connects to the internet", "It connects all components of the computer"],
        ["A programming tool", "Malicious software", "A security firewall", "A system utility", "Malicious software"],
        ["A high-speed internet cable", "Using remote servers to store and access data", "A type of motherboard", "A power saving mode", "Using remote servers to store and access data"],
        ["To locate data", "To identify a device on a network", "To connect Bluetooth devices", "To connect printers", "To identify a device on a network"],
        ["Graphical User Interface", "General User Internet", "Global Utility Interface", "Graphics Usage Integration", "Graphical User Interface"],
        ["Installing drivers", "Starting the computer and loading OS", "Updating software", "Switching tabs", "Starting the computer and loading OS"],
        ["They are the same", "Internet is a service on WWW", "Internet is hardware", "WWW is a device", "Internet is a service on WWW"],
        ["Connects two monitors", "Allows computer to connect to phone", "Converts digital to analog signals", "Provides power backup", "Converts digital to analog signals"]
    ],
    'Computer_Networks_Quiz': [
    ["A group of interconnected programs", "A standalone computer", "A group of interconnected computers", "A software for networking", "A group of interconnected computers"],
    ["LAN covers a large area; WAN covers a small area", "LAN is faster and limited to small areas; WAN covers large areas", "LAN is wireless; WAN is wired", "LAN uses satellites; WAN uses cables", "LAN is faster and limited to small areas; WAN covers large areas"],
    ["Internet Protocol", "Internal Program", "Input Processor", "Integrated Protocol", "Internet Protocol"],
    ["A device identifier", "A unique string of numbers assigned to a device", "A type of memory", "A physical address", "A unique string of numbers assigned to a device"],
    ["To assign IP addresses", "To protect networks", "To translate domain names into IP addresses", "To route data packets", "To translate domain names into IP addresses"],
    ["TCP is connectionless; UDP is connection-oriented", "TCP is slower and unreliable; UDP is faster and reliable", "TCP is connection-oriented; UDP is connectionless", "TCP is for emails; UDP is for web browsing", "TCP is connection-oriented; UDP is connectionless"],
    ["A device ID", "A 32-bit IP address", "A unique hardware identifier assigned to a network interface", "A port number", "A unique hardware identifier assigned to a network interface"],
    ["A device that stores data", "A device that connects networks and routes data", "A device that increases internet speed", "A device that protects from malware", "A device that connects networks and routes data"],
    ["It routes data between networks", "It prevents data loss", "It connects devices within the same network and forwards data", "It protects against viruses", "It connects devices within the same network and forwards data"],
    ["The speed of light", "The number of users on a network", "The maximum data transfer rate of a network", "The number of routers used", "The maximum data transfer rate of a network"],
    ["A device that boosts internet", "A program that monitors emails", "A security system that controls incoming and outgoing network traffic", "A cable connector", "A security system that controls incoming and outgoing network traffic"],
    ["A network protocol", "A hardware device", "A conceptual framework with standard layers for networking", "A wireless network", "A conceptual framework with standard layers for networking"],
    ["3", "5", "7", "9", "7"],
    ["To send emails", "To store data", "Provides reliable data transport and error checking", "To display web pages", "Provides reliable data transport and error checking"],
    ["A way to hide IP addresses", "A code for network hacking", "A 32-bit number that separates the network and host portions of an IP address", "A router setting", "A 32-bit number that separates the network and host portions of an IP address"],
    ["Static IP changes regularly; Dynamic IP remains the same", "Static IP is assigned manually; Dynamic IP is assigned automatically", "Static IP is for phones; Dynamic IP is for computers", "There is no difference", "Static IP is assigned manually; Dynamic IP is assigned automatically"],
    ["It filters unwanted traffic", "It assigns IP addresses to devices automatically", "It controls Wi-Fi signals", "It speeds up networks", "It assigns IP addresses to devices automatically"],
    ["A process for secure file transfer", "A method to detect malware", "Translates private IPs to public IPs for internet access", "A tool to scan networks", "Translates private IPs to public IPs for internet access"],
    ["It defines browser layout", "It converts IP addresses to domains", "It provides electrical power", "Transmits raw data bits over the physical medium", "Transmits raw data bits over the physical medium"],
    ["A cable connector", "A type of virus", "A secure encrypted connection over the internet", "A network cable", "A secure encrypted connection over the internet"]
],
'Operating_System_Quiz': [
    ["A programming language", "A hardware component", "Software that manages hardware and software resources", "A type of computer", "Software that manages hardware and software resources"],
    ["Data encryption", "Managing input/output, memory, and processes", "Designing web applications", "Compiling code", "Managing input/output, memory, and processes"],
    ["A process is a lightweight thread", "A thread is an independent program", "A process is an instance of a program; a thread is a unit of execution within a process", "Threads are slower than processes", "A process is an instance of a program; a thread is a unit of execution within a process"],
    ["Running multiple programs simultaneously", "Using more than one OS", "Installing new hardware", "Sending multiple emails", "Running multiple programs simultaneously"],
    ["To monitor CPU temperature", "To clean RAM", "To determine which process runs next", "To detect malware", "To determine which process runs next"],
    ["Multiprocessing is switching between tasks; multitasking is running on multiple CPUs", "They are the same", "Multiprocessing uses multiple CPUs; multitasking runs multiple tasks on one CPU", "Multitasking needs no OS", "Multiprocessing uses multiple CPUs; multitasking runs multiple tasks on one CPU"],
    ["Memory in the cloud", "A reserved part of CPU", "A technique to use disk space as RAM", "A type of RAM", "A technique to use disk space as RAM"],
    ["A fast-running process", "A process that consumes high memory", "A situation where processes wait indefinitely for resources", "A failed I/O operation", "A situation where processes wait indefinitely for resources"],
    ["Mutual exclusion, hold and wait, no preemption, circular wait", "Shared resources, high memory, system call, thread locking", "No kernel, high CPU, context switch, multitasking", "Multithreading, scheduling, disk I/O, paging", "Mutual exclusion, hold and wait, no preemption, circular wait"],
    ["Switching on the monitor", "Changing file types", "Saving RAM data", "The act of saving and loading process states during a switch", "The act of saving and loading process states during a switch"],
    ["To connect to the internet", "To manage printers", "To enable communication between OS and hardware devices", "To run applications", "To enable communication between OS and hardware devices"],
    ["Kernel mode can access hardware directly; user mode cannot", "User mode has more privileges", "They perform the same role", "User mode controls the OS", "Kernel mode can access hardware directly; user mode cannot"],
    ["Dividing memory into pages for better management", "Copying data to the hard drive", "A network protocol", "Increasing RAM physically", "Dividing memory into pages for better management"],
    ["To install new software", "To perform data encryption", "To manage files and directories", "To manage users", "To manage files and directories"],
    ["Internal fragmentation occurs in external devices", "Internal fragmentation happens in files; external in RAM", "Internal is unused space within partitions; external is scattered free memory", "There is no difference", "Internal is unused space within partitions; external is scattered free memory"],
    ["A system virus", "A hardware component", "An interface between user program and OS services", "A file format", "An interface between user program and OS services"],
    ["A system with high memory", "An OS with quick boot time", "An OS designed for time-critical tasks", "An OS that supports multiple users", "An OS designed for time-critical tasks"],
    ["Monolithic has all services in one kernel; microkernel runs minimal kernel and adds services in user space", "Microkernel is faster than monolithic", "They are the same", "Microkernel runs OS in hardware", "Monolithic has all services in one kernel; microkernel runs minimal kernel and adds services in user space"],
    ["A device driver", "Software that manages disk space", "A program that loads the OS into memory at startup", "A type of antivirus", "A program that loads the OS into memory at startup"],
    ["Moving data from memory to CPU", "Rebooting the system", "Temporarily moving processes between RAM and disk", "Cleaning cache files", "Temporarily moving processes between RAM and disk"]
],
'Programming_Language_Quiz': [
    ["A tool to design graphics", "A language spoken by developers", "A set of instructions to perform a specific task by a computer", "A communication protocol", "A set of instructions to perform a specific task by a computer"],
    ["Compiled is executed line-by-line; Interpreted is pre-compiled", "Compiled languages are for mobile apps; Interpreted for web", "Compiled is translated before execution; Interpreted is translated during execution", "Interpreted languages are faster", "Compiled is translated before execution; Interpreted is translated during execution"],
    ["To store data in memory", "To run the code on a server", "To translate high-level code into machine code", "To execute binary files", "To translate high-level code into machine code"],
    ["A type of function", "A named memory location to store data", "An input statement", "A loop structure", "A named memory location to store data"],
    ["Ways to style code", "Predefined color schemes", "Categories for values like integers, strings, etc.", "File types used in coding", "Categories for values like integers, strings, etc."],
    ["Syntax refers to logic; semantics refers to grammar", "Syntax is variable naming; semantics is looping", "Syntax is the structure; semantics is the meaning", "They mean the same", "Syntax is the structure; semantics is the meaning"],
    ["A method to design websites", "A way to comment code", "A block of code that performs a specific task", "An error handling routine", "A block of code that performs a specific task"],
    ["A repeated if condition", "A loop inside a function", "A function that calls itself", "A return statement", "A function that calls itself"],
    ["Programming based on procedures", "Programming with images", "A paradigm based on objects and classes", "A logic-based coding approach", "A paradigm based on objects and classes"],
    ["Abstraction, Overloading, Looping, Compilation", "Encapsulation, Inheritance, Polymorphism, Abstraction", "Iteration, Compilation, Objects, Syntax", "Inheritance, Syntax, Memory, Data Types", "Encapsulation, Inheritance, Polymorphism, Abstraction"],
    ["A class is an instance; an object is a blueprint", "They are both the same", "A class defines structure; an object is an instance of a class", "Object contains data types; class holds functions", "A class defines structure; an object is an instance of a class"],
    ["Accessing variables outside a class", "Reusing code by deriving new classes from existing ones", "Creating private variables", "Using multiple data types", "Reusing code by deriving new classes from existing ones"],
    ["A technique for memory management", "The ability of different objects to respond to the same message in different ways", "A method of variable declaration", "A way to hide code", "The ability of different objects to respond to the same message in different ways"],
    ["Dividing program into functions", "Binding data and methods into a single unit", "A debugging tool", "A network protocol", "Binding data and methods into a single unit"],
    ["Using only public functions", "Representing only essential features by hiding implementation details", "Naming variables appropriately", "Coding using fewer lines", "Representing only essential features by hiding implementation details"],
    ["Procedural focuses on functions; OOP focuses on objects and classes", "Procedural is outdated", "They are the same", "OOP doesn’t use loops", "Procedural focuses on functions; OOP focuses on objects and classes"],
    ["A command to start a program", "A repeated conditional", "Control structure that repeats a block of code; types include for, while, and do-while", "A data storage method", "Control structure that repeats a block of code; types include for, while, and do-while"],
    ["To improve program speed", "To make the UI better", "To perform different actions based on conditions", "To reduce compilation time", "To perform different actions based on conditions"],
    ["A programming language", "A code testing tool", "An Integrated Development Environment that helps write, test, and debug code", "A network protocol", "An Integrated Development Environment that helps write, test, and debug code"],
    ["Strongly typed allows variable reuse; weakly typed does not", "Strongly typed languages enforce type rules strictly; weakly typed do not", "They refer to variable naming", "Strongly typed uses integers only", "Strongly typed languages enforce type rules strictly; weakly typed do not"]
],
'Politics_Quiz': [
    ["Ram Nath Kovind", "Pranab Mukherjee", "Droupadi Murmu", "Venkaiah Naidu", "Droupadi Murmu"],
    ["Mahatma Gandhi", "Sardar Vallabhbhai Patel", "Jawaharlal Nehru", "Rajendra Prasad", "Jawaharlal Nehru"],
    ["Elect the President", "Enforce law", "Make laws", "Conduct elections", "Make laws"],
    ["238", "245", "250", "Rajya Sabha has no fixed number", "245"],
    ["500", "543", "552", "545", "543"],
    ["Jawaharlal Nehru", "B. R. Ambedkar", "Mahatma Gandhi", "Sardar Patel", "B. R. Ambedkar"],
    ["4 years", "6 years", "5 years", "Till death", "5 years"],
    ["Chief Justice of India", "Parliament", "President of India", "Council of Ministers", "President of India"],
    ["Article 12", "Article 14", "Article 19", "Article 21", "Article 19"],
    ["21 years", "25 years", "35 years", "30 years", "25 years"],
    ["Supreme Court", "Election Commission of India", "Parliament", "Lok Sabha", "Election Commission of India"],
    ["Sushil Chandra", "Sunil Arora", "Rajiv Kumar", "T. N. Seshan", "Rajiv Kumar"],
    ["Bharatiya Janata Party", "Indian National Congress", "Socialist Party", "None", "Indian National Congress"],
    ["Bharat Janta Party", "Bharatiya Janata Party", "Bharatiya Justice Party", "Bharatiya Jan Jagran Party", "Bharatiya Janata Party"],
    ["Indian National Congress", "Indian National Committee", "Indian National Cabinet", "Indian National Council", "Indian National Congress"],
    ["To head the Cabinet", "To control police", "To act as the ceremonial head and ensure governance as per the Constitution", "To lead the legislative assembly", "To act as the ceremonial head and ensure governance as per the Constitution"],
    ["Government formed by one party", "Rule by President", "Government formed by multiple parties", "Minority government", "Government formed by multiple parties"],
    ["President of India", "Prime Minister", "Chief Justice of India", "Speaker of Lok Sabha", "Chief Justice of India"],
    ["Article 352", "Article 360", "Article 356", "Article 370", "Article 356"],
    ["Lok Sabha", "Rajya Sabha", "State Assembly", "Gram Sabha", "Rajya Sabha"]
],
'Sports_Quiz': [
    ["France", "Germany", "Argentina", "Brazil", "Argentina"],
    ["Cristiano Ronaldo", "Lionel Messi", "Ali Daei", "Sunil Chhetri", "Cristiano Ronaldo"],
    ["Virat Kohli", "Sachin Tendulkar", "MS Dhoni", "Rahul Dravid", "Sachin Tendulkar"],
    ["5", "6", "7", "8", "6"],
    ["Indian Players League", "Indian Professional League", "Indian Premier League", "International Premier League", "Indian Premier League"],
    ["Abhinav Bindra", "Leander Paes", "Milkha Singh", "Neeraj Chopra", "Abhinav Bindra"],
    ["Football", "Basketball", "Cricket", "Hockey", "Football"],
    ["3", "4", "5", "6", "5"],
    ["USA", "France", "Greece", "Italy", "Greece"],
    ["Cricket", "Ice Hockey", "Basketball", "Baseball", "Ice Hockey"],
    ["Rafael Nadal", "Roger Federer", "Novak Djokovic", "Pete Sampras", "Novak Djokovic"],
    ["127", "147", "155", "160", "147"],
    ["Russia", "Germany", "USA", "China", "USA"],
    ["80 minutes", "90 minutes", "70 minutes", "100 minutes", "90 minutes"],
    ["P. T. Usha", "Neeraj Chopra", "Abhinav Bindra", "Milkha Singh", "Milkha Singh"],
    ["PV Sindhu", "Mirabai Chanu", "Mary Kom", "Dutee Chand", "Mirabai Chanu"],
    ["Volleyball", "Tennis", "Basketball", "Football", "Basketball"],
    ["Virat Kohli", "Sachin Tendulkar", "Ricky Ponting", "Kumar Sangakkara", "Sachin Tendulkar"],
    ["18 inches", "20 inches", "22 inches", "24 inches", "18 inches"],
    ["Football", "Tennis", "Badminton", "Table Tennis", "Tennis"]
],
'Finance_Quiz': [
    ["Gross Domestic Product", "General Domestic Policy", "Government Debt Policy", "Global Development Plan", "Gross Domestic Product"],
    ["State Bank of India", "Ministry of Finance", "Reserve Bank of India", "NITI Aayog", "Reserve Bank of India"],
    ["Decrease in prices", "Rise in employment", "Increase in general price levels", "Fall in production", "Increase in general price levels"],
    ["Excess of income over expenditure", "Excess of exports over imports", "Government's expenditure exceeds revenue", "Surplus in trade", "Government's expenditure exceeds revenue"],
    ["Reserve Bank of India", "Rural Banking Institution", "Revenue Board of India", "Registered Bank of India", "Reserve Bank of India"],
    ["Regulating foreign trade", "Printing currency", "Controlling inflation and money supply", "Collecting taxes", "Controlling inflation and money supply"],
    ["Rate at which RBI lends to commercial banks", "Interest paid on savings", "Loan repayment rate", "Foreign exchange rate", "Rate at which RBI lends to commercial banks"],
    ["Currency exchange counter", "Market for agricultural goods", "Platform to buy/sell company shares", "Online payment gateway", "Platform to buy/sell company shares"],
    ["Won", "Yuan", "Baht", "Yen", "Yen"],
    ["Government savings scheme", "Bank deposit", "Investment pool managed by professionals", "Company loan", "Investment pool managed by professionals"],
    ["GST", "Excise duty", "Income tax", "Sales tax", "Income tax"],
    ["Foreign Direct Investment", "Financial Development Index", "Fiscal Deposit Initiative", "Foreign Debt Investment", "Foreign Direct Investment"],
    ["Permanent Account Number", "Primary Account Number", "Public Account Number", "Personal Allocation Number", "Permanent Account Number"],
    ["A bank account number", "A rating of your financial health and creditworthiness", "Your loan amount", "A financial planning tool", "A rating of your financial health and creditworthiness"],
    ["Market with rising prices", "Market where goods are cheap", "Market with falling prices", "Market for commodities", "Market with falling prices"],
    ["Goods and Services Tax", "Government Sales Tax", "Gross Settlement Tax", "Global Services Tariff", "Goods and Services Tax"],
    ["Bond", "Loan", "Share", "Mutual fund", "Share"],
    ["Initial Public Offering", "Indian Portfolio Offer", "Interest Payment Option", "Investors' Preferred Offer", "Initial Public Offering"],
    ["Profiting from stock trading", "Running a business without registration", "Legal status of inability to pay debts", "Avoiding taxes", "Legal status of inability to pay debts"],
    ["SEBI", "RBI", "NITI Aayog", "IRDAI", "SEBI"]
],
'International_Affairs_Quiz': [
    ["Ban Ki-moon", "Kofi Annan", "Antonio Guterres", "Tedros Adhanom", "Antonio Guterres"],
    ["India", "China", "USA", "Indonesia", "China"],
    ["China", "Japan", "South Korea", "Vietnam", "Japan"],
    ["Toronto", "Vancouver", "Ottawa", "Montreal", "Ottawa"],
    ["Amazon", "Yangtze", "Mississippi", "Nile", "Nile"],
    ["1940", "1945", "1950", "1939", "1945"],
    ["China", "Brazil", "Japan", "USA", "Japan"],
    ["Euro", "Pound Sterling", "Dollar", "Franc", "Pound Sterling"],
    ["Asia", "Africa", "Europe", "South America", "Africa"],
    ["UNICEF", "WHO", "WTO", "UNDP", "WHO"],
    ["China", "Germany", "India", "USA", "USA"],
    ["Seoul", "Busan", "Pyongyang", "Incheon", "Seoul"],
    ["Germany", "Italy", "France", "Spain", "France"],
    ["International Criminal Court", "UN Security Council", "World Bank", "UNESCO", "International Criminal Court"],
    ["Indira Gandhi", "Margaret Thatcher", "Sirimavo Bandaranaike", "Golda Meir", "Sirimavo Bandaranaike"],
    ["USA and Canada", "Russia and China", "India and Bangladesh", "Argentina and Chile", "USA and Canada"],
    ["Gobi", "Sahara", "Arctic", "Kalahari", "Antarctic"],
    ["A trade agreement between Asia and Europe", "UK leaving the European Union", "A UN migration treaty", "US-Mexico border wall plan", "UK leaving the European Union"],
    ["Monaco", "Vatican City", "Nauru", "San Marino", "Vatican City"],
    ["Spanish", "Portuguese", "French", "English", "Portuguese"]
],
'Physics_Quiz': [
    ["Newton", "Joule", "Pascal", "Watt", "Newton"],
    ["Albert Einstein", "Galileo Galilei", "Isaac Newton", "Nikola Tesla", "Isaac Newton"],
    ["3 x 10⁶ m/s", "3 x 10⁸ m/s", "3 x 10⁵ km/h", "3 x 10⁷ m/s", "3 x 10⁸ m/s"],
    ["Energy and Power relation", "Mass-energy equivalence", "Motion formula", "Gravitational law", "Mass-energy equivalence"],
    ["Volt", "Ampere", "Watt", "Ohm", "Ohm"],
    ["Gravitational force", "Magnetic force", "Friction", "Centripetal force", "Friction"],
    ["Newton’s First Law", "Newton’s Second Law", "Law of Inertia", "Pascal’s Law", "Newton’s First Law"],
    ["9.8 m/s²", "8.9 m/s²", "10.5 m/s²", "9.2 m/s²", "9.8 m/s²"],
    ["Voltmeter", "Galvanometer", "Ammeter", "Barometer", "Ammeter"],
    ["Nuclear fission", "Nuclear fusion", "Combustion", "Chemical reaction", "Nuclear fusion"],
    ["Joule", "Watt", "Newton", "Volt", "Watt"],
    ["Concave lens", "Convex lens", "Biconvex lens", "Plano-convex lens", "Concave lens"],
    ["V = IR", "F = ma", "P = IV", "E = mc²", "V = IR"],
    ["Height of a wave", "Speed of a wave", "Time between wave crests", "Number of waves per second", "Number of waves per second"],
    ["Proton", "Electron", "Neutron", "Photon", "Electron"],
    ["Kinetic energy", "Thermal energy", "Potential energy", "Nuclear energy", "Potential energy"],
    ["Bending of light around objects", "Spreading of light", "Bouncing back of light", "Bending of light when it passes from one medium to another", "Bending of light when it passes from one medium to another"],
    ["Scalars have magnitude only; vectors have magnitude and direction", "Vectors are imaginary", "Scalars are directionless vectors", "Scalars are always negative", "Scalars have magnitude only; vectors have magnitude and direction"],
    ["Newton’s Third Law", "Archimedes' Principle", "Pascal’s Law", "Bernoulli’s Principle", "Pascal’s Law"],
    ["Diffraction", "Reflection", "Interference", "Dispersion", "Dispersion"]
],
'Chemistry_Quiz': [
    ["Au", "Ag", "Gd", "Go", "Au"],
    ["5", "7", "6", "9", "7"],
    ["Dmitri Mendeleev", "Antoine Lavoisier", "Robert Boyle", "John Dalton", "Antoine Lavoisier"],
    ["4", "6", "8", "12", "6"],
    ["Oxygen", "Hydrogen", "Nitrogen", "Carbon Dioxide", "Nitrogen"],
    ["NaCl", "KCl", "CaCl₂", "MgCl", "NaCl"],
    ["Water", "Hydrochloric Acid", "Hydrogen Peroxide", "Sodium Hydroxide", "Hydrogen Peroxide"],
    ["Chart of acids and bases", "Arrangement of atoms", "Arrangement of elements based on atomic number", "Table of molecules", "Arrangement of elements based on atomic number"],
    ["Oxygen", "Chlorine", "Fluorine", "Nitrogen", "Fluorine"],
    ["Evaporation", "Sublimation", "Condensation", "Melting", "Sublimation"],
    ["Acid + Acid = Water", "Acid + Base = Salt and Water", "Base + Base = Acid", "Acid + Salt = Water", "Acid + Base = Salt and Water"],
    ["CH₄", "C₂H₆", "C₂H₂", "CH₃OH", "CH₄"],
    ["10 g/mol", "12 g/mol", "18 g/mol", "16 g/mol", "18 g/mol"],
    ["Element with different electrons", "Same number of protons but different neutrons", "Atoms with same mass", "Charged atoms", "Same number of protons but different neutrons"],
    ["Citric acid", "Sulfuric acid", "Acetic acid", "Nitric acid", "Acetic acid"],
    ["Highly reactive elements", "Group 18 elements with full outer shells", "Radioactive metals", "Liquid elements", "Group 18 elements with full outer shells"],
    ["Washing soda", "Baking soda", "Caustic soda", "Lime water", "Baking soda"],
    ["Lead", "Graphite", "Carbon", "Charcoal", "Graphite"],
    ["Oxidation", "Reduction", "Sublimation", "Decomposition", "Oxidation"],
    ["Ethane", "Propane", "Butane", "Methane", "Methane"]
],
'Mathematics_Quiz': [
    ["3.00", "3.12", "3.14", "3.18", "3.14"],
    ["10", "11", "12", "13", "12"],
    ["πr²", "2πr", "πd", "2rπ", "πr²"],
    ["20", "25", "30", "35", "30"],
    ["4", "6", "8", "9", "8"],
    ["90°", "180°", "270°", "360°", "180°"],
    ["10 cm", "20 cm", "25 cm", "30 cm", "20 cm"],
    ["54", "56", "58", "60", "56"],
    ["5", "6", "7", "8", "6"],
    ["3", "4", "5", "6", "4"],
    ["Heptagon", "Hexagon", "Octagon", "Nonagon", "Octagon"],
    ["Rational is repeating/terminating, irrational is non-repeating", "Rational numbers are negative", "Irrational numbers are whole numbers", "Both are integers", "Rational is repeating/terminating, irrational is non-repeating"],
    ["a² + b² = c²", "a² - b² = c²", "a² + b² = c", "a + b = c²", "a² + b² = c²"],
    ["100", "60", "120", "720", "120"],
    ["7", "70", "700", "7000", "700"],
    ["12", "18", "24", "48", "24"],
    ["Most frequent number", "Middle number", "Difference between high and low", "Average", "Most frequent number"],
    ["13", "14", "15", "17", "13"],
    ["l × w × h", "4 × a", "a³", "a × a", "a³"],
    ["0", "1", "Undefined", "Infinity", "0"]
]
}
