ques_list = {'Computer Fundamentals Quiz':
    ["What is the full form of CPU?",
    "What does RAM stand for?",
    "What is an input device?",
    "What is the function of the operating system?",
    "What is the difference between hardware and software?",
    "What does ROM stand for?",
    "What is a computer network?",
    "What is the use of a printer?",
    "What is a file in computing?",
    "What is the function of a compiler?",
    "What is binary number system?",
    "What is the primary function of the ALU?",
    "What is the purpose of a motherboard?",
    "What is a computer virus?",
    "What is cloud computing?",
    "What is the use of an IP address?",
    "What is a GUI?",
    "What is meant by booting a computer?",
    "What is the difference between the Internet and the World Wide Web?",
    "What is the function of a modem?"
],
'Computer Networks Quiz':
    ["What is a computer network?",
    "What is the difference between LAN and WAN?",
    "What is the full form of IP?",
    "What is an IP address?",
    "What is the purpose of DNS in networking?",
    "What is the difference between TCP and UDP?",
    "What is a MAC address?",
    "What is a router and what does it do?",
    "What is the function of a switch in a network?",
    "What is meant by bandwidth in networking?",
    "What is a firewall in computer networks?",
    "What is the OSI model in networking?",
    "How many layers are there in the OSI model?",
    "What is the role of the transport layer in the OSI model?",
    "What is a subnet mask?",
    "What is the difference between static and dynamic IP addresses?",
    "What is DHCP and how does it work?",
    "What is NAT in computer networks?",
    "What is the function of the physical layer in the OSI model?",
    "What is a VPN and what is it used for?"],
'Operating System Quiz':
    ["What is an operating system?",
    "What are the main functions of an operating system?",
    "What is the difference between a process and a thread?",
    "What is multitasking in operating systems?",
    "What is the purpose of a scheduler in an OS?",
    "What is the difference between multiprocessing and multitasking?",
    "What is virtual memory?",
    "What is a deadlock in operating systems?",
    "What are the necessary conditions for a deadlock to occur?",
    "What is a context switch?",
    "What is the role of a device driver in an operating system?",
    "What is the difference between kernel mode and user mode?",
    "What is paging in memory management?",
    "What is the function of the file system in an OS?",
    "What is the difference between internal and external fragmentation?",
    "What is a system call?",
    "What is a real-time operating system (RTOS)?",
    "What is the difference between a monolithic kernel and a microkernel?",
    "What is a bootloader?",
    "What is swapping in operating systems?"],
'Programming Language Quiz':
    ["What is a programming language?",
    "What is the difference between a compiled and an interpreted language?",
    "What is the purpose of a compiler?",
    "What is a variable in programming?",
    "What are data types in programming languages?",
    "What is the difference between syntax and semantics?",
    "What is a function or method in programming?",
    "What is recursion in programming?",
    "What is object-oriented programming (OOP)?",
    "What are the four main principles of OOP?",
    "What is the difference between a class and an object?",
    "What is inheritance in OOP?",
    "What is polymorphism in programming?",
    "What is encapsulation?",
    "What is abstraction in programming?",
    "What is the difference between procedural and object-oriented programming?",
    "What is a loop and what types of loops are available?",
    "What is the purpose of conditional statements in programming?",
    "What is an IDE and how is it used in programming?",
    "What is the difference between strongly typed and weakly typed languages?"],
'Politics Quiz':
    ["Who is the current President of India?",
    "Who was the first Prime Minister of India?",
    "What is the main function of the Parliament of India?",
    "How many members are there in the Rajya Sabha?",
    "How many members are there in the Lok Sabha?",
    "Who is known as the Father of the Indian Constitution?",
    "What is the tenure of the President of India?",
    "Who appoints the Prime Minister of India?",
    "Which Article of the Indian Constitution deals with Fundamental Rights?",
    "What is the minimum age required to become the Prime Minister of India?",
    "Which body conducts elections in India?",
    "Who is the current Chief Election Commissioner of India?",
    "Which political party was founded by Jawaharlal Nehru?",
    "What is the full form of BJP?",
    "What is the full form of INC in Indian politics?",
    "What is the role of the Governor in an Indian state?",
    "What does the term ‘coalition government’ mean?",
    "Who is the head of the Indian Judiciary?",
    "Which article in the Constitution allows the President to impose President's Rule in a state?",
    "Which house of the Indian Parliament is considered the upper house?"],
'Sports Quiz':
    ["Which country won the FIFA World Cup in 2022?",
    "Who holds the record for the most goals in international football?",
    "Which cricketer is known as the 'Master Blaster'?",
    "How many players are there in a volleyball team?",
    "What is the full form of IPL in cricket?",
    "Who is the first Indian to win an individual Olympic gold medal?",
    "Which sport is known as the 'king of sports'?",
    "How many rings are there in the Olympic logo?",
    "In which country were the first modern Olympics held?",
    "What is the national sport of Canada?",
    "Who has won the most Grand Slam titles in tennis (male)?",
    "What is the maximum score in a single frame of snooker?",
    "Which country has won the most Olympic medals in total?",
    "What is the length of a standard football match?",
    "Who is known as the 'Flying Sikh' of India?",
    "Which Indian female athlete won silver at the Tokyo Olympics 2020 in weightlifting?",
    "In which sport would you perform a slam dunk?",
    "Which cricketer has scored the most centuries in international cricket?",
    "What is the diameter of a basketball hoop?",
    "In which sport is the Davis Cup awarded?"],
'Finance Quiz':
    ["What is the full form of GDP?",
    "Which organization is responsible for printing currency in India?",
    "What does the term 'inflation' mean?",
    "What is a budget deficit?",
    "What is the full form of RBI?",
    "What is the primary function of a central bank?",
    "What does 'repo rate' refer to in banking?",
    "What is meant by 'stock market'?",
    "What is the currency of Japan?",
    "What is a mutual fund?",
    "Which tax is levied directly on income?",
    "What does 'FDI' stand for?",
    "What is the full form of PAN in Indian finance?",
    "What is a credit score?",
    "What does 'bear market' mean?",
    "What is the full form of GST?",
    "Which financial instrument represents ownership in a company?",
    "What is the full form of IPO?",
    "What does 'bankruptcy' mean?",
    "Which Indian financial body regulates the stock market?"],
'International Affairs':
    ["Who is the current Secretary-General of the United Nations?",
    "Which country has the largest population in the world?",
    "Which country is known as the Land of the Rising Sun?",
    "What is the capital city of Canada?",
    "Which is the longest river in the world?",
    "In which year was the United Nations founded?",
    "Which country hosted the 2020 Summer Olympics (held in 2021)?",
    "Which currency is used in the United Kingdom?",
    "Which continent has the most number of countries?",
    "Which international organization deals with global public health?",
    "Which country has the highest GDP in the world?",
    "What is the capital of South Korea?",
    "Which country is famous for the Eiffel Tower?",
    "Which international court is located in The Hague, Netherlands?",
    "Who was the first woman Prime Minister in the world?",
    "Which two countries share the longest international border?",
    "Which desert is the largest in the world by area?",
    "What is Brexit?",
    "Which country is the smallest in the world by area?",
    "What is the official language of Brazil?"],
'Physics Quiz':
    ["What is the SI unit of force?",
    "Who formulated the laws of motion?",
    "What is the speed of light in a vacuum?",
    "What does E = mc² represent?",
    "What is the unit of electrical resistance?",
    "What is the force that opposes motion between two surfaces in contact?",
    "Which law explains why we wear seat belts?",
    "What is the acceleration due to gravity on Earth?",
    "What is the device used to measure electric current?",
    "What is the primary source of energy for the Sun?",
    "What is the SI unit of power?",
    "Which type of lens is used to correct short-sightedness?",
    "What is Ohm's Law?",
    "What is the frequency of a wave?",
    "Which subatomic particle carries a negative charge?",
    "What type of energy is stored in a stretched rubber band?",
    "What is refraction of light?",
    "What is the difference between scalar and vector quantities?",
    "Which principle is used in the working of a hydraulic press?",
    "What is the name of the phenomenon where white light splits into its component colors?"],
'Chemistry Quiz':
    ["What is the chemical symbol for gold?",
    "What is the pH value of pure water?",
    "Who is known as the father of modern chemistry?",
    "What is the atomic number of carbon?",
    "Which gas is most abundant in the Earth's atmosphere?",
    "What is the formula of common salt?",
    "What is the chemical name of H₂O₂?",
    "What is the periodic table?",
    "Which element has the highest electronegativity?",
    "What is the process of converting a solid directly into a gas called?",
    "What is an acid-base neutralization reaction?",
    "What is the chemical formula of methane?",
    "What is the molecular mass of water?",
    "What is an isotope?",
    "Which acid is found in vinegar?",
    "What are noble gases?",
    "What is the common name for sodium bicarbonate?",
    "Which element is used in pencils?",
    "What is the process of rusting chemically known as?",
    "What is the main component of natural gas?"],
'Biology Quiz':
    ["What is the basic unit of life?",
    "Which organelle is known as the powerhouse of the cell?",
    "What is the function of red blood cells?",
    "Which part of the plant conducts photosynthesis?",
    "What is the scientific name of humans?",
    "Which vitamin is produced when the skin is exposed to sunlight?",
    "What is the largest organ in the human body?",
    "What is the function of the lungs?",
    "What is the process by which plants make their own food?",
    "Which organ is responsible for pumping blood throughout the body?",
    "What is DNA?",
    "What is the name of the pigment that gives plants their green color?",
    "Which part of the brain controls balance and coordination?",
    "How many chromosomes do humans have?",
    "What is a herbivore?",
    "What is the role of white blood cells?",
    "What is the scientific study of animals called?",
    "What gas do plants absorb from the atmosphere for photosynthesis?",
    "What is the function of the kidneys?",
    "Which blood group is known as the universal donor?"],
'Mathematics Quiz':
    ["What is the value of π (pi) up to two decimal places?",
    "What is the square root of 144?",
    "What is the formula for the area of a circle?",
    "What is 15% of 200?",
    "What is the value of 2³?",
    "What is the sum of interior angles of a triangle?",
    "What is the perimeter of a square with side length 5 cm?",
    "What is the result of 7 × 8?",
    "How many sides does a hexagon have?",
    "What is the value of x in the equation 2x + 3 = 11?",
    "What is the name of a polygon with 8 sides?",
    "What is the difference between a rational and an irrational number?",
    "What is the formula for the Pythagorean theorem?",
    "What is the factorial of 5?",
    "What is the place value of 7 in the number 3,742?",
    "What is the least common multiple (LCM) of 6 and 8?",
    "What is the mode in a data set?",
    "What is the next prime number after 11?",
    "What is the formula for the volume of a cube?",
    "What is the slope of a horizontal line?"]
}
